---
- name: EC2 Instance Management
  ec2:
    assign_public_ip: "{{ item.assign_public_ip | default(omit) }}"
    aws_access_key: "{{ item.aws_access_key | default(omit) }}"
    aws_secret_key: "{{ item.aws_secret_key | default(omit) }}"
    count: "{{ item.count | default(omit) }}"
    count_tag: "{{ item.count_tag | default(omit) }}"
    ebs_optimized: "{{ item.ebs_optimized | default(omit) }}"
    ec2_url: "{{ item.ec2_url | default(omit) }}"
    exact_count: "{{ item.exact_count | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    group_id: "{{ item.group_id | default(omit) }}"
    id: "{{ item.id | default(omit) }}"
    image: "{{ item.image }}"
    instance_ids: "{{ item.instance_ids | default(omit) }}"
    instance_initiated_shutdown_behavior: "{{ item.instance_initiated_shutdown_behavior | default(omit) }}"
    instance_profile_name: "{{ item.instance_profile_name | default(omit) }}"
    instance_tags: "{{ item.instance_tags | default(omit) }}"
    instance_type: "{{ item.instance_type }}"
    kernal: "{{ item.kernel | default(omit) }}"
    key_name: "{{ item.key_name | default(omit) }}"
    monitoring: "{{ item.monitoring | default(omit) }}"
    network_interfaces: "{{ item.network_interfaces | default(omit) }}"
    placement_group: "{{ item.placement_group | default(omit) }}"
    private_ip: "{{ item.private_ip | default(omit) }}"
    profile: "{{ item.profile | default(omit) }}"
    ramdisk: "{{ item.ramdisk | default(omit) }}"
    region: "{{ item.region | default(omit) }}"
    security_token: "{{ item.security_token | default(omit) }}"
    source_dest_check: "{{ item.source_dest_check | default(omit) }}"
    spot_launch_group: "{{ item.spot_launch_group | default(omit) }}"
    spot_price: "{{ item.spot_price | default(omit) }}"
    spot_type: "{{ item.spot_type | default(omit) }}"
    spot_wait_timeout: "{{ item.spot_wait_timeout | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    tenancy: "{{ item.tenancy | default(omit) }}"
    termination_protection: "{{ item.termination_protection | default(omit) }}"
    user_data: "{{ item.user_data  | default(omit) }}"
    validate_certs: "{{ item.validate_certs | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
    vpc_subnet_id: "{{ item.vpc_subnet_id | default(omit) }}"
    wait: "{{ item.wait | default(omit) }}"
    wait_timeout: "{{ item.wait_timeout | default(omit) }}"
    zone: "{{ item.zone | default(omit) }}"
  with_items: "{{ ec2_list }}"
