---

- name: Group Management
  group:
    gid: "{{ item.gid | default(omit) }}"
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
  with_items: "{{ group_list }}"
